# Please consult our docs for more info: https://www.librechat.ai/docs/configuration/docker_override

# TO USE THIS FILE, FIRST UNCOMMENT THE LINE ('services:')

# THEN UNCOMMENT ONLY THE SECTION OR SECTIONS CONTAINING THE CHANGES YOU WANT TO APPLY
# SAVE THIS FILE AS 'docker-compose.override.yaml'
# AND USE THE 'docker compose build' & 'docker compose up -d' COMMANDS AS YOU WOULD NORMALLY DO

# WARNING: YOU CAN ONLY SPECIFY EVERY SERVICE NAME ONCE (api, mongodb, meilisearch, ...)
# IF YOU WANT TO OVERRIDE MULTIPLE SETTINGS IN ONE SERVICE YOU WILL HAVE TO EDIT ACCORDINGLY

# EXAMPLE: if you want to use the config file and the latest numbered release docker image the result will be:

# services:
#   api:
#     volumes:
#     - type: bind
#       source: ./librechat.yaml
#       target: /app/librechat.yaml
#     image: ghcr.io/danny-avila/librechat:latest

# ---------------------------------------------------

services:
  # Override api service: build with Python support and mount MCP code
  api:
    build:
      context: .
      dockerfile: Dockerfile.librechat-python
    volumes:
      - ./librechat.yaml:/app/librechat.yaml
      - C:\Users\noahc\PycharmProjects\langextract:/opt/mcp/contractextract:ro
    environment:
      - HOST=0.0.0.0
      - MONGO_URI=mongodb://mongodb:27017/LibreChat
      - MEILI_HOST=http://meilisearch:7700
      - RAG_PORT=${RAG_PORT:-8000}
      - RAG_API_URL=http://rag_api:${RAG_PORT:-8000}
      - PYTHONUNBUFFERED=1
    depends_on:
      mongodb:
        condition: service_healthy
        required: true
      meilisearch:
        condition: service_healthy
        required: true
      rag_api:
        condition: service_started
        required: true
      contractextract-db:
        condition: service_healthy
        required: true

  mongodb:
    image: mongo:7
    restart: unless-stopped
    user: "" # Override UID/GID from base - let mongo use its own user
    healthcheck:
      test: ["CMD-SHELL", "mongosh --quiet --eval 'db.adminCommand({ ping: 1 }).ok' | grep 1 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s
    volumes:
      - mongo-data:/data/db

  meilisearch:
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7700/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s
    volumes:
      - meili_data:/meili_data

  rag_api:
    image: ghcr.io/danny-avila/librechat-rag-api-dev:latest
    healthcheck:
      test: ["CMD-SHELL", "python - <<'PY'\nimport sys,urllib.request\ntry:\n  r=urllib.request.urlopen('http://localhost:8000/health', timeout=2)\n  sys.exit(0 if r.status==200 else 1)\nexcept Exception:\n  sys.exit(1)\nPY"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s
    environment:
      EMBEDDINGS_PROVIDER: ollama
      EMBEDDINGS_MODEL: nomic-embed-text
      OLLAMA_BASE_URL: http://host.docker.internal:11434
      MONGODB_URL: mongodb://mongodb:27017
      MEILI_HTTP_ADDR: http://meilisearch:7700
    depends_on:
      meilisearch:
        condition: service_healthy
        required: true
      mongodb:
        condition: service_healthy
        required: true

  # PostgreSQL for ContractExtract MCP server
  contractextract-db:
    image: postgres:15-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: contractextract
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: contractextract_pass
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d contractextract"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    volumes:
      - contractextract-db-data:/var/lib/postgresql/data

volumes:
  mongo-data:
  meili_data:
  contractextract-db-data:


# # LOCAL BUILD
#   api:
#     image: librechat
#     build:
#       context: .
#       target: node

# # BUILD FROM LATEST IMAGE
#   api:
#     image: ghcr.io/danny-avila/librechat-dev:latest

# # BUILD FROM LATEST IMAGE (NUMBERED RELEASE)
#   api:
#     image: ghcr.io/danny-avila/librechat:latest

# # BUILD FROM LATEST API IMAGE
#   api:
#     image: ghcr.io/danny-avila/librechat-dev-api:latest

# # BUILD FROM LATEST API IMAGE (NUMBERED RELEASE)
#   api:
#     image: ghcr.io/danny-avila/librechat-api:latest

# # ADD SAML CERT FILE
#   api:
#     volumes:
#     - type: bind
#       source: ./your_cert.pem
#       target: /app/your_cert.pem

# # ADD MONGO-EXPRESS
#   mongo-express:
#     image: mongo-express
#     container_name: mongo-express
#     environment:
#       ME_CONFIG_MONGODB_SERVER: mongodb
#       ME_CONFIG_BASICAUTH_USERNAME: admin
#       ME_CONFIG_BASICAUTH_PASSWORD: password
#     ports:
#       - '8081:8081'
#     depends_on:
#       - mongodb
#     restart: always

# # USE MONGODB V4.4.18 - FOR OLDER CPU WITHOUT AVX SUPPORT
#   mongodb:
#     image: mongo:4.4.18

# # DISABLE THE MONGODB CONTAINER - YOU NEED TO SET AN ALTERNATIVE MONGODB URI IN THE .ENV FILE
#   api:
#     environment:
#       - MONGO_URI=${MONGO_URI}
#   mongodb:
#     image: tianon/true
#     command: ""
#     entrypoint: ""

# # EXPOSE MONGODB PORTS - USE CAREFULLY, THIS MAKES YOUR DATABASE VULNERABLE TO ATTACKS
#   mongodb:
#     ports:
#       - 27018:27017

# # DISABLE MEILISEARCH
#   meilisearch:
#     profiles:
#       - donotstart

# # EXPOSE MEILISEARCH PORTS - DO NOT USE THE DEFAULT VALUE FOR THE MASTER KEY IF YOU DO THIS
#   meilisearch:
#     ports:
#       - 7700:7700

# # USE RAG API IMAGE WITH LOCAL EMBEDDINGS SUPPORT
#  rag_api:
#    image: ghcr.io/danny-avila/librechat-rag-api-dev:latest
# # For Linux user:
#    extra_hosts:
#      - "host.docker.internal:host-gateway"

# # ADD OLLAMA
#  ollama:
#    image: ollama/ollama:latest
#    deploy:
#      resources:
#        reservations:
#          devices:
#            - driver: nvidia
#              capabilities: [compute, utility]
#    ports:
#      - "11434:11434"
#    volumes:
#      - ./ollama:/root/.ollama

# # ADD LITELLM BASIC - NEED TO CONFIGURE litellm-config.yaml, ONLY NEED ENV TO ENABLE REDIS FOR CACHING OR LANGFUSE FOR MONITORING
#  litellm:
#    image: ghcr.io/berriai/litellm:main-latest
#    volumes:
#      - ./litellm/litellm-config.yaml:/app/config.yaml
#      - ./litellm/application_default_credentials.json:/app/application_default_credentials.json # only if using Google Vertex
#    ports:
#      - "4000:8000"
#    command: [ "--config", "/app/config.yaml", "--port", "8000", "--num_workers", "8" ]
#    environment:
#      OPENAI_API_KEY: none ## needs to be set if ollama's openai api compatibility is used
#      GOOGLE_APPLICATION_CREDENTIALS: /app/application_default_credentials.json ## only if using Google Vertex
#      REDIS_HOST: redis
#      REDIS_PORT: 6379
#      REDIS_PASSWORD: RedisChangeMe
#      LANGFUSE_PUBLIC_KEY: pk-lf-RandomStringFromLangfuseWebInterface
#      LANGFUSE_SECRET_KEY: sk-lf-RandomStringFromLangfuseWebInterface
#      LANGFUSE_HOST: http://langfuse-server:3000

# # ADD LITELLM CACHING
#  redis:
#    image: redis:7-alpine
#    command:
#    - sh
#    - -c # this is to evaluate the $REDIS_PASSWORD from the env
#    - redis-server --appendonly yes --requirepass $$REDIS_PASSWORD ## $$ because of docker-compose
#    environment:
#      REDIS_PASSWORD: RedisChangeMe
#    volumes:
#    - ./redis:/data

# # ADD LITELLM MONITORING
#  langfuse-server:
#    image: ghcr.io/langfuse/langfuse:latest
#    depends_on:
#      - db
#    ports:
#      - "3000:3000"
#    environment:
#      - NODE_ENV=production
#      - DATABASE_URL=postgresql://postgres:PostgresChangeMe@db:5432/postgres
#      - NEXTAUTH_SECRET=ChangeMe
#      - SALT=ChangeMe
#      - NEXTAUTH_URL=http://localhost:3000
#      - TELEMETRY_ENABLED=${TELEMETRY_ENABLED:-true}
#      - NEXT_PUBLIC_SIGN_UP_DISABLED=${NEXT_PUBLIC_SIGN_UP_DISABLED:-false}
#      - LANGFUSE_ENABLE_EXPERIMENTAL_FEATURES=${LANGFUSE_ENABLE_EXPERIMENTAL_FEATURES:-false}
#  db:
#    image: postgres
#    restart: always
#    environment:
#      - POSTGRES_USER=postgres
#      - POSTGRES_PASSWORD=PostgresChangeMe
#      - POSTGRES_DB=postgres
#    volumes:
#      - ./postgres:/var/lib/postgresql/data
